import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import { MenuComponent } from "@/components/Menu";
import "react-toastify/dist/ReactToastify.css";

const inter = Rubik({
  weight: ["300", "400", "500", "700", "900"],
  style: ["normal", "normal"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Photographer Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className={`${inter.className} flex flex-col my-10 p-10 sm:flex-row`}>
      <MenuComponent />
      <div className="w-3/4">{children}</div>
    </div>
  );
}
