import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";

const inter = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Photographer Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="w-full h-full">
      <body
        className={`${inter.className} flex flex-col lg:flex-row w-full h-full `}
      >
        <div className="w-full h-full">{children}</div>
      </body>
    </html>
  );
}
